version: '3.8'
services:
  web:
    build: ./web
    ports:
      - '3000:3000'
    depends_on:
      - mongo
    networks:
      - app-network

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
